name: mesheryctl End-to-End Tests
on:
  workflow_dispatch:
    inputs:
      profile_name:
        description: "performance profile to use"
        required: false
      profile_filename:
        description: "test configuration file"
        required: false
  # scheduled to run at the 43rd minute of every 12th hour
  schedule:
    - cron: '43 */12 * * *'

jobs:
  manual-test-out-of-cluster:
    name: Manual e2e Test (Out of Cluster)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        k8s_version: ['v1.20.11', 'v1.21.5', 'v1.22.2']
    steps:
      - name: Setup Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: ${{ matrix.k8s_version }}
          driver: docker

      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H.%M.%S')"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Performance Tests
        uses: layer5io/meshery-smp-action@master
        with:
          provider_token: ${{ secrets.PROVIDER_TOKEN }}
          platform: docker
          profile_name: ${{ github.event.inputs.profile_name }}
          profile_filename: ${{ github.event.inputs.profile_filename }}
          test_name: '${{ steps.date.outputs.date }}'