name: Scheduled Benchmark Tests
on:
  # for triggering manually, provide a token
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: false
      profile_name:
        description: "performance profile to use"
        required: false
      profile_filename:
        description: "test configuration file"
        required: false
  # scheduled to run at every Thursday at 13:22
  schedule:
    - cron: '22 13 * * THU'

jobs:
  manual-test:
    name: Manual Benchmark Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        service-mesh: ['istio', 'linkerd', 'osm']
    steps:
      - name: Setup Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: 'v1.22.2'
          driver: docker

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Service Mesh and Deploy Application
        run: |
          chmod +x .github/workflows/scripts/${{ matrix.service-mesh }}_deploy.sh
          .github/workflows/scripts/${{ matrix.service-mesh }}_deploy.sh
        shell: bash
        
      - name: Run Benchmark Tests
        uses: navendu-pottekkat/meshery-smp-action@update-action/navendu-pottekkat
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: docker
          profile_name: ${{ github.event.inputs.profile_name }}
          profile_filename: ${{ github.event.inputs.profile_filename }}
          endpoint_url: ${{env.ENDPOINT_URL}}
          service_mesh: ${{env.SERVICE_MESH}}

  scheduled-test:
    name: Scheduled Benchmark Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    strategy:
      matrix:
        service-mesh: ['istio', 'linkerd', 'osm']
    steps:
      - name: Setup Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.23.2'
          kubernetes version: 'v1.22.2'
          driver: docker

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Service Mesh and Deploy Application
        run: |
          chmod +x .github/workflows/scripts/${{ matrix.service-mesh }}_deploy.sh
          .github/workflows/scripts/${{ matrix.service-mesh }}_deploy.sh
        shell: bash
        
      - name: Run Benchmark Tests
        uses: navendu-pottekkat/meshery-smp-action@update-action/navendu-pottekkat
        with:
          provider_token: ${{ secrets.MESHERY_TOKEN }}
          platform: docker
          profile_name: istio-benchmark
          profile_filename: istio-test-config
